# Generated by Django 5.1.3 on 2024-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('pan_number', models.CharField(max_length=10)),
                ('fund_name', models.CharField(max_length=255)),
                ('investment_type', models.CharField(choices=[('EQUITY', 'Equity'), ('DEBT', 'Debt'), ('MUTUAL_FUND', 'Mutual Fund'), ('BONDS', 'Bonds')], max_length=50)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invested_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
